services:
  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    container_name: minio_local
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ProjectMLOps:/data
    env_file:
      - mi.env  # Reference to the .env file containing environment variables
    command: server /data --console-address ":9001"

volumes: 
  ProjectMLOps:
    external: true # This indicated that the volume has been created before running this command 

 
